### ISSUE TITLE
Misleading Property Name

### ISSUE THREAD

**Issue by dragos-rosca** [osstotalsoft/rocket-webapp-components#11]
https://github.com/osstotalsoft/rocket-webapp-components/blob/27d56030e965011ef675f5cc067c23085b5b09ad/components/IconCollapseCard/IconCollapseCard.js#L30

This property is called header and we assumed it's the header of the card. This is false, this is the summary version of the card and it will disappear when you expand the card.

**Comment by VCuzmin** [comment]
Will be fixed in the upcoming release!

**Comment by VCuzmin** [comment]
Fixed in the latest version
