### ISSUE TITLE
Could not find the referenced rule "transparent" and "justIcon" in "makeStyles"

### ISSUE THREAD

**Issue by alexandra-c** [osstotalsoft/rocket-webapp-components#119]
After updating the components in my project to the latest version (V 2.9.36) I'm getting this strangewarnings in my console...
![image](https://user-images.githubusercontent.com/46926675/133846850-99e261e8-537d-4b91-a8be-fe379e71e702.png)

**Comment by andra-sava** [comment]
This is a known issue from material-ui, and from my understanding it should be fixed in the next version(v5): https://github.com/mui-org/material-ui/issues/15511
