### ISSUE TITLE
problem with grouped options

### ISSUE THREAD

**Issue by cerbugabriel** [osstotalsoft/rocket-webapp-components#12]
https://github.com/osstotalsoft/rocket-webapp-components/blob/27d56030e965011ef675f5cc067c23085b5b09ad/components/Autocomplete/Autocomplete.js#L174-L181

if i use the grouping functionality and try simpleValue it doesn't work

Grouping shape is: 
```javascript
{
label: 'the name of the group'
options: [ /* the normal option list */ ]
}
```

**Comment by VCuzmin** [comment]
Will be fixed in the upcoming release!

**Comment by VCuzmin** [comment]
Fixed in the latest version
