### ISSUE TITLE
Debounce Should Not Be Active as Default #6

### ISSUE THREAD

**Issue by alexandra-c** [osstotalsoft/rocket-webapp-components#3]
referenced from #https://github.com/osstotalsoft/generator-webapp-rocket/issues/6

https://github.com/osstotalsoft/rocket-webapp-components/blob/bbb408101cfe730d9287e5d9ad3a9e73490aa536/src/core/CustomTextField/CustomTextField.js#L122

The debounce functionality should be opt in not active by default

please set default to 0

**Comment by VCuzmin** [comment]
fixed!
