### ISSUE TITLE
Can Not Set Start Adornment

### ISSUE THREAD

**Issue by dragos-rosca** [osstotalsoft/rocket-webapp-components#39]
https://github.com/osstotalsoft/rocket-webapp-components/blob/f7df9db370ce8c86ea0727b3e18e085e716eb2fa/components/CustomTextField/CustomTextField.js#L64-L108

This doesn't let me set the startAdornment, only the endAdornment

**Comment by VCuzmin** [comment]
Fixed in the latest version
