### ISSUE TITLE
The onClick event is not handled properly in IconCollapseCard

### ISSUE THREAD

**Issue by DCosti** [osstotalsoft/rocket-webapp-components#51]
The onClick event is not handled properly in IconCollapseCard when title contains a button. When clicking a button that is added in the card's header, it triggers the onToggle method instead of it's own onClick handler.

**Only the method handled by the button should be triggered and not the toggle.**

See: https://bit.dev/totalsoft_oss/react-mui/icon-collapse-card?example=5ff71e4e7e8f360019c1b584

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/41594981/104181848-1f89b980-5418-11eb-8613-43ba77d1ce9d.png)

**Comment by VCuzmin** [comment]
https://github.com/osstotalsoft/rocket-webapp-components/issues/56
