### ISSUE TITLE
Disabled Text Field Label For isNumber Is Displayed Wrong 

### ISSUE THREAD

**Issue by dragos-rosca** [osstotalsoft/rocket-webapp-components#60]
In the custom text field (components/CustomTextField/CustomTextField.js) there is a problem with the label when the field is disabled. The label doesn't see the value in number format and it's drawn in the value space and when the field is short, the label is drawn over the value.
When the text field has a text value it behaves normally and the label stays above the value.
Please see the picture below:

![Bad Label Position](https://user-images.githubusercontent.com/26022019/107751686-696f0380-6d26-11eb-9a4d-2af3017dde65.png)

**Comment by VCuzmin** [comment]
According to this example: https://codesandbox.io/s/dbfz3?file=/demo.js,  you must pass 
```getInputRef={inputRef} ``` property to NumberFormatCustom. In current component it was set up as follows:     

```
ref={(ref) => {
        inputRef(ref ? ref.inputElement : null);
      }}
```

To convince, change ```getInputRef={inputRef}``` to 
```
ref={(ref) => {
        inputRef(ref ? ref.inputElement : null);
      }}
```

After that, you will notice that the label and the value will be overlapped.

**Comment by VCuzmin** [comment]
See 2.6.13 version
