### ISSUE TITLE
DateTime component providing an onClick event listener to a child of a button element

### ISSUE THREAD

**Issue by abrezuica** [osstotalsoft/rocket-webapp-components#66]
DateTime component is providing an onClick event listener to a child of a button element as follows: 
```
    const simplePickerProps = {
        keyboardIcon: <CalendarToday fontSize="small" onClick={handleSetOpen(true)} />,
        ...
    }
```
causing a warning in the console:
![dateTimeBug](https://user-images.githubusercontent.com/59456269/114563880-7f426b80-9c78-11eb-90eb-93df2864d112.PNG)

**Comment by alexandra-c** [comment]
Related https://github.com/mui-org/material-ui/issues/22804
