### ISSUE TITLE
The Autocomplete component does not overlap the card it comes from

### ISSUE THREAD

**Issue by RobertBboghian** [osstotalsoft/rocket-webapp-components#71]
![Capture](https://user-images.githubusercontent.com/69892365/119777614-16811c80-becf-11eb-8359-b92efdcc8b50.PNG)

**Comment by alexandra-c** [comment]
Can you give us a bit more context? What exactly is the card it comes from? Is it a modal? What kind of modal? There are two of them.
Thanks

**Comment by RobertBboghian** [comment]
Yes, sure. It's not a modal, it's a 'card' imported from @material-ui/core

**Comment by abrezuica** [comment]
Hey, @RobertBboghian 
This issue is now fixed. You should upgrade your bit components to the latest version (2.7.5) in order for the changes to apply. 
Thanks :D
